spring:
  application:
    name: rag_langchain4j

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  datasource:
    dataBaseName: ${POSTGRES_DB}
    url: jdbc:postgresql://localhost:5438/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  pgvector:
    table: ${PGVECTOR_TABLE:embeddings}
    dimension: ${PGVECTOR_DIMENSION:1536}

  ai:
    openai:
        api-key: ${OPENAI_API_KEY}
        base-url: https://api.openai.com/v1
        timeout: 30s


app:
  upload:
    temp-dir: ${TEMP_DIR}
  allowed-content-types:
    - application/pdf
    - text/plain
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - image/jpeg
    - image/png

server:
  max-http-request-size: MAX_HTTP_REQUEST_SIZE

docling:
  based-url: ${DOCLING_BASE_URL}


management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

logging:
  level:
    .dev.langchain4j: DEBUG
